### ISSUE TITLE
First draft of the climate_data function

### ISSUE THREAD

**Issue by RSO9192** [Risk-Team/pyAEZ-climate-module#1]
Hi all, 

I have made the first draft of the function. It needs testing, which I did not yet fully complete myself but you can give it a go! 

I think we can improve several things including parallelization. I will be working on it in the next few days. 

@kboonma @DarioSpiller @NokuzaSezo97

**Comment by NokuzaSezo97** [comment]
Hi @RSO9192,

Apologies for the late reply. I tested out the combined function of the climate data extraction **climate_data_pyAEZ** function, the process. At first, the processing is going ok, until I encountered the **dimensionality error** message (error message attached) during bias correction of solar radiation. Could you check it out?

Error Code:
---------------------------------------------------------------------------
DimensionalityError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_36196\2231194287.py in <cell line: 9>()
      7 bias = True
      8 
----> 9 mylist = portal.climate_data_pyAEZ(country = country, cordex_domain= cordex_dom, rcp = rcp, model= model_no, 
     10                           years_up_to= yr_upto, years_obs= yr_obs, bias_correction= bias)

D:\pyAEZ-climate-module\functions\climate_data_pyAEZ.py in climate_data_pyAEZ(country, cordex_domain, rcp, model, years_up_to, years_obs, bias_correction, historical, obs, buffer, xlim, ylim)
    223     for variable in ["tasmax", "tasmin", "pr", "hurs", "rsds", "sfcWind"]:
    224         print(f"[bold yellow]Processing variable: {variable}[/bold yellow]")
--> 225         result = climate_data(
    226             country=country,
    227             xlim=xlim,

D:\pyAEZ-climate-module\functions\climate_data_pyAEZ.py in climate_data(country, cordex_domain, rcp, model, years_up_to, variable, years_obs, obs, bias_correction, historical, buffer, xlim, ylim)
    180             ref = downloaded_obs[0]
    181             print("[bold yellow]Performing bias correction with eqm[/bold yellow]")
--> 182             QM_mo = sdba.EmpiricalQuantileMapping.train(ref, hist, group='time.month', kind='*' if variable == 'pr' else '+')
    183             proj_bs = QM_mo.adjust(proj)
    184             print("[bold yellow]Done![/bold yellow]")

c:\ProgramData\Anaconda3\lib\site-packages\xclim\sdba\adjustment.py in train(cls, ref, hist, **kwargs)
    175 
    176         if not skip_checks:
--> 177             (ref, hist), train_units = cls._harmonize_units(ref, hist)
    178 
    179             if "group" in kwargs:

c:\ProgramData\Anaconda3\lib\site-packages\xclim\sdba\adjustment.py in <genexpr>(.0)
    132 
    133         return (
--> 134             convert_units_to(inda, target, context="infer") for inda in inputs
    135         ), target
    136 

c:\ProgramData\Anaconda3\lib\site-packages\xclim\core\units.py in convert_units_to(source, target, context)
    417 
    418         with units.context(context or "none"):
--> 419             out = source.copy(data=units.convert(source.data, source_unit, target_unit))
    420             out.attrs["units"] = target_cf_unit
    421             return out

c:\ProgramData\Anaconda3\lib\site-packages\pint\facets\plain\registry.py in convert(self, value, src, dst, inplace)
   1026             return value
   1027 
-> 1028         return self._convert(value, src, dst, inplace)
   1029 
   1030     def _convert(

c:\ProgramData\Anaconda3\lib\site-packages\pint\facets\context\registry.py in _convert(self, value, src, dst, inplace)
    402                 value, src = src._magnitude, src._units
    403 
--> 404         return super()._convert(value, src, dst, inplace)
    405 
    406     def _get_compatible_units(

c:\ProgramData\Anaconda3\lib\site-packages\pint\facets\nonmultiplicative\registry.py in _convert(self, value, src, dst, inplace)
    252 
    253         if not (src_offset_unit or dst_offset_unit):
--> 254             return super()._convert(value, src, dst, inplace)
    255 
    256         src_dim = self._get_dimensionality(src)

c:\ProgramData\Anaconda3\lib\site-packages\pint\facets\plain\registry.py in _convert(self, value, src, dst, inplace, check_dimensionality)
   1061 
   1062         if isinstance(factor, DimensionalityError):
-> 1063             raise factor
   1064 
   1065         # factor is type float and if our magnitude is type Decimal then

DimensionalityError: Cannot convert from 'watt / meter ** 2' ([mass] / [time] ** 3) to 'joule / meter ** 2' ([mass] / [time] ** 2)

**Comment by RSO9192** [comment]
Thanks @NokuzaSezo97 . 

It seems that era5 and CORDEX have different units for solar radiation. I will check this.

**Comment by RSO9192** [comment]
Hi @NokuzaSezo97, it should be fixed now. Basically, ERA5 data for rsds was in J and not in W so I had to convert it

**Comment by RSO9192** [comment]
Any updates @kboonma  @NokuzaSezo97 ?

**Comment by RSO9192** [comment]
Error was fixed
